import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MenuComponent from "./components/MenuComponents/MenuComponent";
import MobileMenuComponent from "@/app/components/MenuComponents/MobileMenuComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props : any) {
  props.params.menuSet = "Intro";
  props.params.changeMenu = (str : string) => {
    props.params.menuSet = str;
    console.log("menu set to: " + props.params.menuSet);
//    props.params.menuComp();
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MenuComponent params={props.params}/>
        <MobileMenuComponent />
        <div className="content">
          {props.children}
        </div>
        <div className='rippleContainer'>
          <div className="ripple"></div>
          <div className="ripple"></div>
          <div className="ripple"></div>
        </div>
      </body>
    </html>
  );
}
