name: Deploy App

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REGISTRY_NAME }}:${{ secrets.IMAGE_NAME }} \
            --build-arg CONTACT_EMAIL=${{ secrets.CONTACT_EMAIL }} \
            -f Dockerfile .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REGISTRY_NAME }}:${{ secrets.IMAGE_NAME }}

  Pull:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REGISTRY_NAME }}:${{ secrets.IMAGE_NAME }}
      - name: Stop Docker Container
        run: |
          if [ $(docker ps -q --filter name=${{ secrets.IMAGE_NAME }}) ]; then
              currentPort=$(docker inspect -f '{{range $p, $conf := .NetworkSettings.Ports}} {{$p}} {{end}}' ${{ secrets.IMAGE_NAME }} | awk '{print $1}' | awk -F'->' '{print $1}')
              docker stop ${{ secrets.IMAGE_NAME }}
              docker rm ${{ secrets.IMAGE_NAME }}
          fi
      - name: Wait for Docker Container to Stop
        run: |
          while [ $(docker ps -q --filter name=${{ secrets.IMAGE_NAME }}) ]; do
              sleep 1
          done

  Run:
    runs-on: self-hosted
    needs: Pull
    steps:
      - name: Run Docker Container
        run: |
          docker run -d \
          -p 9340:3000 \
          -v /tmp/resume.pdf:/tmp/resume.pdf \
          --restart unless-stopped \
          --name ${{ secrets.IMAGE_NAME }} \
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REGISTRY_NAME }}:${{ secrets.IMAGE_NAME }}