name: Verify PR Builds

on:
  pull_request:
    branches: [dev, master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Install Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: "Install Dependencies"
        run: npm install
      - name: "Lint"
        run: npm run lint
      - name: "Build"
        run: npm run build
