name: Verify PR Builds

on:
  pull_request:
    branches: [dev, master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Install Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: "Setup Environment"
        run: |
          echo "REACT_APP_API_URL=http://localhost:3000" >> .env
          echo "NEXT_PUBLIC_POSTHOG_KEY=${{ secrets.POSTHOG_KEY }}" >> .env
          echo "NEXT_PUBLIC_POSTHOG_URL=${{ secrets.POSTHOG_URL }}" >> .env

      - name: "Install Dependencies"
        run: npm install
      - name: "Lint"
        run: npm run lint
      - name: "Build"
        run: npm run build
